### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by valkedev** [tonik/wordpress-theme-boilerplate#14]
looks like Gulp 3 + Node 12 doesn't work. Unfortunately package is useless for now
```
ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/var/www/wp/immersion/wp-content/themes/immersion/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/var/www/wp/immersion/wp-content/themes/immersion/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/var/www/wp/immersion/wp-content/themes/immersion/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by idChef** [comment]
You need to downgrade your node version, it is easy with nvm.

https://stackoverflow.com/a/58771749

**Comment by erickocrs** [comment]
Gulp 4+ Fix
https://github.com/erickocrs/wordpress-theme-boilerplate/tree/gulp_fix

Now its need's to use some, gulp.series(['func']), gulp.parallel(['func']) to execute an array of functions...
also declare callBackFunctions too

😀👍
